const level1 = new Level(
    [
        new Pufferfish(),
        new Pufferfish(),
        new Pufferfish(),
        new Endboss(),
    ],
    [
        new Light(),
    ],
    [
        new Background('img/3_background/layers/5_water/d1.png', -1440),
        new Background('img/3_background/layers/4_fondo_2/d1.png', -1440),
        new Background('img/3_background/layers/3_fondo_1/d1.png', -1440),
        new Background('img/3_background/layers/2_floor/d1.png', -1440),
        new Background('img/3_background/layers/5_water/d2.png', -720),
        new Background('img/3_background/layers/4_fondo_2/d2.png', -720),
        new Background('img/3_background/layers/3_fondo_1/d2.png', -720),
        new Background('img/3_background/layers/2_floor/d2.png', -720),
        new Background('img/3_background/layers/5_water/d1.png', 0),
        new Background('img/3_background/layers/4_fondo_2/d1.png', 0),
        new Background('img/3_background/layers/3_fondo_1/d1.png', 0),
        new Background('img/3_background/layers/2_floor/d1.png', 0),
        new Background('img/3_background/layers/5_water/d2.png', 720),
        new Background('img/3_background/layers/4_fondo_2/d2.png', 720),
        new Background('img/3_background/layers/3_fondo_1/d2.png', 720),
        new Background('img/3_background/layers/2_floor/d2.png', 720),
        new Background('img/3_background/layers/5_water/d1.png', 1440),
        new Background('img/3_background/layers/4_fondo_2/d1.png', 1440),
        new Background('img/3_background/layers/3_fondo_1/d1.png', 1440),
        new Background('img/3_background/layers/2_floor/d1.png', 1440),
        new Background('img/3_background/layers/5_water/d2.png', 2160),
        new Background('img/3_background/layers/4_fondo_2/d2.png', 2160),
        new Background('img/3_background/layers/3_fondo_1/d2.png', 2160),
        new Background('img/3_background/layers/2_floor/d2.png', 2160),
        new Background('img/3_background/layers/5_water/d1.png', 2880),
        new Background('img/3_background/layers/4_fondo_2/d1.png', 2880),
        new Background('img/3_background/layers/3_fondo_1/d1.png', 2880),
        new Background('img/3_background/layers/2_floor/d1.png', 2880),
        new Background('img/3_background/layers/5_water/d2.png', 3600),
        new Background('img/3_background/layers/4_fondo_2/d2.png', 3600),
        new Background('img/3_background/layers/3_fondo_1/d2.png', 3600),
        new Background('img/3_background/layers/2_floor/d2.png', 3600),
    ]
);